library(ggplot2)
library(dplyr)
library(broom)
d=read.csv('D:/DA/SUV Predictions data.csv')
print(d)
head(d)
tail(d)
print(is.null(d))
names(d)
nrow(d)
ncol(d)
mean(d$Salary)
print(unique(d))
print(median(d$Age))
hist(d$Salary)
boxplot(d$Salary~d$Age)
pie(table(d$Age))
print(plot(Salary~Age,data=d))
li=lm(Salary~Age,data=d)
print(li)
print(summary(li))
i<-ggplot(d,aes(x=Salary,y=Age))+geom_point()
print(i)
i<-i+geom_smooth(method = 'lm',col='blue')
print(i)
